import Head from "next/head";
import React from "react";
import Cards from "../components/Card/Card";

const automation = () => {
  return (
    <div className="bg-[#333333] min-h-screen">
      <Head>
        <title>Daco | Automation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-2">
        <div className="pt-4">
          <Cards />
        </div>
      </main>
    </div>
  );
};

export default automation;
