import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import { motion as m } from "framer-motion";
import { useState } from "react";
import Loader from "../components/Loader";
export default function Home() {
  const [loading, setLoading] = useState(true);
  return (
    <m.div
      className="bg-orange-100"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.75, ease: "easeOut" }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading ? (
        <m.div key="loader">
          <Loader loading={loading} setLoading={setLoading} />
        </m.div>
      ) : (
        <main>
          <Navbar />
          <div className="my-96 p-1">
            <h1 className="text-6xl text-center lg:text-right lg:text-9xl">
              Happy Pickle
            </h1>
          </div>

          <div className="flex justify-between">
            <div>
              <h2>Design</h2>
              <h2>Company</h2>
              <h2>2022</h2>
            </div>
            <div>
              <h3>This pickle gonna make you smile.</h3>
              <h3>Scottish designs to make you happy</h3>
              <h3>click contact for cool</h3>
            </div>
          </div>
        </main>
      )}
    </m.div>
  );
}
